package com.pockt.infrastructure.exception;

public enum ErrorCode {
    INVALID_OTP,
    OTP_EXPIRED,
    OTP_MAX_ATTEMPTS,
    PHONE_ALREADY_REGISTERED,
    USER_NOT_FOUND,
    RECEIVER_NOT_FOUND,
    WALLET_NOT_FOUND,
    WALLET_INACTIVE,
    INSUFFICIENT_BALANCE,
    SELF_TRANSFER,
    DUPLICATE_TRANSFER,
    INVALID_AMOUNT,
    RATE_LIMIT_EXCEEDED,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    FORBIDDEN,
    BAD_CREDENTIALS,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
